<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.36" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\CSS\" />
    <Folder Include="wwwroot\Font\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Core.Entities\Core.Entities.csproj" />
  </ItemGroup>

  <Import Project="..\Blazor.Contellation.Controls\Blazor.Contellation.Controls.projitems" Label="Shared" />

</Project>
