<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FontAwesomes\**" />
    <EmbeddedResource Remove="FontAwesomes\**" />
    <None Remove="FontAwesomes\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="6.0.36" />
    <PackageReference Include="Microsoft.JSInterop" Version="6.0.32" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.Entities\Core.Entities.csproj" />
  </ItemGroup>

  <Import Project="..\Core.Libraries.Connect\Core.Libraries.Connect.projitems" Label="Shared" />

  <Import Project="..\Core.Libraries.Enums\Core.Libraries.Enums.projitems" Label="Shared" />

  <Import Project="..\Core.Libraries.Helpers\Core.Libraries.Helpers.projitems" Label="Shared" />

  <Import Project="..\Core.Libraries.Interfaces\Core.Libraries.Interfaces.projitems" Label="Shared" />

  <Import Project="..\Core.Libraries.PythonNet\Core.Libraries.PythonNet.projitems" Label="Shared" />

  <Import Project="..\Core.Libraries.Structs\Core.Libraries.Structs.projitems" Label="Shared" />

  <Import Project="..\Core.Libraries.Interops\Core.Libraries.Interops.projitems" Label="Shared" />

</Project>
